[signal]
start_len = 1000
end_len = 1000
sample_rate = 1
u0 = [0.001]
te = [3600]
dc = [0.0]

[[noise]]
type='simple_predict_error'
mean_amplitude = [0]
var_amplitude = [0.1]
dur_samples_amplitude = [15]
sample_rate = 1

[[noise]]
type='sine_with_phase_error'
mean_phase= [0]
var_phase = [15]
dur_samples_phase = [150]
sample_rate = 1
period = [200]
amplitude = [2]
phase = [0]

#[[noise]]
#type='sine'
#period = [220]
#amplitude = [2]
#phase = [0]

#[[noise]]
#type='uniform'
#min_amplitude = [1]
#max_amplitude = [2]

[[pre-noise]]
type='skip'
