[signal]
start_len = 1000
end_len = 1000
sample_rate = 1
u0 = [0.01, 0.1, 0.01]
te = [1000, 12000, 1000]

# make it so low that it is essentially not there
[[noise]]
type='gaussian'
mean=0
variance=[0.00000001]
