[signal]
start_len = 1000
end_len = 1000
sample_rate = 1
u0 = [0.001, 0.1, 0.06]
te = [3600, 86400, 3600]
dc = [0.0, 10.0, 6.0]

# make it so low that it is essentially not there
[[noise]]
type='gaussian'
mean=0
variance=[0.00000001]

[[pre-noise]]
type='flare-gj1234'
amplitude=[10, 20, 8]
tot_time=[3000]
