[signal]
start_len = 1000
end_len = 1000
sample_rate = 15
u0 = 100000.0
te = 1
dc = 0.0

[[noise]]
type='simple_predict_error'
mean_amplitude = 0
var_amplitude = 0.08
dur_samples_amplitude = 15
sample_rate = 15

[[pre-noise]]
type='skip'
